[package]
name = "Bartholomew"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poise = "0.5.6"
sqlx = "0.7.2"
tokio = { version = "1.33.0", features = ["full"] }
